// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvul95d84_V1L_8nUTF7Un5TX89pUCcyU',
    appId: '1:355222662653:web:4cf3cea05dba44046abd94',
    messagingSenderId: '355222662653',
    projectId: 'mobile-cloud-messenger',
    authDomain: 'mobile-cloud-messenger.firebaseapp.com',
    storageBucket: 'mobile-cloud-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllCcXjca9__2DJ-RuQoMfboma77dPzGc',
    appId: '1:355222662653:android:3b4eda54d930699d6abd94',
    messagingSenderId: '355222662653',
    projectId: 'mobile-cloud-messenger',
    storageBucket: 'mobile-cloud-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XadMtniTka2xw8GvjZL7sTHGhNAwoDA',
    appId: '1:355222662653:ios:6cca5fd20bdda81f6abd94',
    messagingSenderId: '355222662653',
    projectId: 'mobile-cloud-messenger',
    storageBucket: 'mobile-cloud-messenger.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3XadMtniTka2xw8GvjZL7sTHGhNAwoDA',
    appId: '1:355222662653:ios:6cca5fd20bdda81f6abd94',
    messagingSenderId: '355222662653',
    projectId: 'mobile-cloud-messenger',
    storageBucket: 'mobile-cloud-messenger.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvul95d84_V1L_8nUTF7Un5TX89pUCcyU',
    appId: '1:355222662653:web:4860bd3e3ce205c76abd94',
    messagingSenderId: '355222662653',
    projectId: 'mobile-cloud-messenger',
    authDomain: 'mobile-cloud-messenger.firebaseapp.com',
    storageBucket: 'mobile-cloud-messenger.firebasestorage.app',
  );
}
